### ISSUE TITLE
Tundra failed to build under gcc-4.4.4

### ISSUE THREAD

**Issue by AdrienHerubel** [deplinenoise/tundra#69]
Warning in the lua source code. Probably a false positive. Works fine with gcc-4.6.1

$ gcc-4.4 -c -DNDEBUG -DTD_STANDALONE -Isrc -Ilua/src -Wall -Werror -O3  -o tundra-output/linux-gcc-release-standalone/__base_lua_host/lua/src/lcode.o lua/src/lcode.c
cc1: warnings being treated as errors
lua/src/lcode.c: In function ‘luaK_exp2RK’:  
lua/src/lcode.c:243: error: ‘v’ may be used uninitialized in this function  
lua/src/lcode.c:272: note: ‘v’ was declared here  
$ gcc-4.4 --version
gcc-4.4 (GCC) 4.4.4
